tweag/capability

capability.cabal

New release of `generic-lens` was available.
And now, the version is standard on stackage: https://stackage.org/package/generic-lens .
Please relax the restriction of `generic-lens` for dependency resolver.
See also: https://github.com/kcsongor/generic-lens/compare/1.0.0.2...1.1.0.0

Relax a restriction of generic-lens

---

ChangeLog.md
capability.cabal

- Bump version number
- Update changelog
See package candidate: https://hackage.haskell.org/package/capability-0.2.0.0/candidate

Release version 0.2.0.0

---

nix/nixpkgs/default.nix
nix/nixpkgs/src.json

Running `nix-shell` fails due to `builder = nixcfg.shell;` being impure (see NixOS/nixpkgs#30399).
This commit fixes this by using the idiomatic nix2 method of nixpkgs pinning. The `sha256` has changed as it is now the hash of the unpacked archive.
See: https://github.com/tweag/capability/issues/69

Pin nixpkgs in nix2 style

---

capability.cabal
examples/Reader.hs
src/Capability/Error.hs
src/Capability/Reader.hs
src/Capability/State.hs
src/Capability/Stream.hs
src/Capability/TypeOf.hs
src/Capability/Writer.hs

Fixes #65.
Introduces a poly-kinded type family to allow users to associate tags to type, and corresponding type synonyms for all capabilities to shorten constraint declarations.
Also changes the 'Reader' example to make use of this feature.

Introducing `TypeOf` type family

---

capability.cabal
examples/Reader.hs
examples/State.hs
src/Capability/Constraints.hs
src/Capability/Reader.hs
src/Capability/Reader/Internal/Class.hs
src/Capability/State.hs
src/Capability/State/Internal/Class.hs

This change allows callers of the `Capability.State.zoom` and `Capability.Reader.magnify` functions to pass along a set of capabilities from the current monadic context to the focusing action. Retained capabilities are specified via a typelevel parameter of kind `[(* -> *) -> Constraint]`.
Implementation relies on `unsafeCoerce` to convert a dictionary for a wrapped monad instance to the original monad.
Fixes #46.

Capability-retaining `zoom` and `magnify`

---

capability.cabal
examples/Error.hs
examples/Reader.hs
examples/State.hs
src/Capability/Constraints.hs
src/Capability/Context.hs
src/Capability/Error.hs
src/Capability/Reader/Internal/Class.hs
src/Capability/State/Internal/Class.hs

This PR introduces a `Capability.Context.context` function that generalizes the approach taken in #73 to allow users to derive arbitrary new capabilities from the current context via a specified newtype combinator. The `zoom` and `magnify` functions are rewritten in terms of this helper.
The interface of `zoom` and `magnify` is also simplified a bit. Previously, those had a constraint of the form:
```
forall m'. HasState outertag outer m' => HasState innertag inner (t m')
```
but it seems that those were not necessary. We now only request that:
```
HasState innertag inner (t m)
```
without quantifying over all `m'`s.
*NOTE:* Based on #73 ; change base branch before merging !

Allow arbitrary capability derivations

---

ChangeLog.md
capability.cabal
examples/Reader.hs
examples/Sink.hs
examples/State.hs
examples/Test.hs
examples/WordCount.hs
examples/Writer.hs
src/Capability.hs
src/Capability/Constraints.hs
src/Capability/Reader/Internal/Class.hs
src/Capability/Reader/Internal/Strategies.hs
src/Capability/Sink.hs
src/Capability/Sink/Internal/Class.hs
src/Capability/Sink/Internal/Strategies.hs
src/Capability/Source.hs
src/Capability/Source/Internal/Class.hs
src/Capability/Source/Internal/Strategies.hs
src/Capability/State/Internal/Class.hs
src/Capability/State/Internal/Strategies.hs
src/Capability/State/Internal/Strategies/Common.hs
src/Capability/Stream.hs
src/Capability/Writer.hs

We now have:
```
Sink     Source
/   \    /   \
/     \  /     \
Writer   State    Reader
```
HasStream has been renamed (with deprecated aliases for compat) to HasSink, to
illustrate the symmetry.
WIP because I need to review myself, and probably also fix examples.
Fixes #63.

Introduce HasSource, and make superclasses

---

stack.yaml

My guess is that the LTS version at the time did not support features required by this project. If so, that's no longer the case: now the LTS resolver can be used. That seems like a good idea to me.

Use LTS resolver instead of nightly

---

capability.cabal

Bump version bounds for GHC 8.8 Stackage snapshot support.
Closes https://github.com/tweag/capability/issues/78

Support nightly-2020-01-05 (GHC 8.8)

---

.gitignore
capability.cabal
src/Capability.hs
src/Capability/Context.hs
src/Capability/Derive.hs
src/Capability/Error.hs
src/Capability/Reader.hs
src/Capability/Reader/Internal/Class.hs
src/Capability/Sink.hs
src/Capability/Source.hs
src/Capability/State.hs
src/Capability/State/Internal/Class.hs
src/Capability/Writer.hs

I've tried to make the Haddock look good, basically.

Preparing for release: api and documentation

---

src/Capability/Writer.hs

`Capability.HasWriter.writer` was calling itself in a loop instead of calling `Capability.HasWriter.writer_`.

Fix loop in Capability.HasWriter.writer

---

capability.cabal
examples/Reflection.hs
examples/Test.hs
src/Capability.hs
src/Capability/Error.hs
src/Capability/Reader/Internal/Class.hs
src/Capability/Reflection.hs
src/Capability/Sink/Internal/Class.hs
src/Capability/Source/Internal/Class.hs
src/Capability/State/Internal/Class.hs
src/Capability/Writer.hs

Allows users to define ad-hoc interpretations of capabilities using the functions `Capability.Reflection.interpret_` and `Capability.Reflection.interpret` by providing a dictionary, i.e. a record of functions, that defines an implementation of the capability.
The details are explained in the Haddock documentation of `Capability.Reflection`. A reference to the top-level `Capability` Haddock documentation is added as well.
Examples are defined in `examples/Reflection.hs`.

Implement reflection for ad-hoc interpreters

---

capability.cabal
default.nix
examples/CountLog.hs
examples/Error.hs
examples/Reader.hs
nix/nixpkgs/default.nix
src/Capability/Accessors.hs
src/Capability/Constraints.hs
src/Capability/Error.hs
src/Capability/Reader/Internal/Class.hs
src/Capability/Reader/Internal/Strategies.hs
src/Capability/Reflection.hs
src/Capability/Sink/Internal/Class.hs
src/Capability/Sink/Internal/Strategies.hs
src/Capability/Source/Internal/Class.hs
src/Capability/Source/Internal/Strategies.hs
src/Capability/State/Internal/Class.hs
src/Capability/State/Internal/Strategies.hs
src/Capability/State/Internal/Strategies/Common.hs
src/Capability/TypeOf.hs
src/Capability/Writer.hs

Visibility of the kind argument changed in
https://gitlab.haskell.org/ghc/ghc/-/commit/012257c15f584069500af2953ab70856f9a1470e
.
This makes capability compatible with GHC 8.10 .
We still need to change the dependencies to be recent enough.

Fix the visible type arguments of proxy#

---

ChangeLog.md
capability.cabal

- Bump version number
- Update changelog
See package candidate: https://hackage.haskell.org/package/capability-0.4.0.0/candidate

Release 0.4.0.0

---

README.md

This example fails to compile with the newest versions of `capability`, due to missing instances.

Adding missing HasSource / HasSink to documentation example

---

examples/Writer.hs
src/Capability/Writer.hs

This is a useful function, present in the corresponding mtl library,
that can be defined in terms of the existing `pass` primitive.
However, doing so is nontrivial (I spent quite a while banging my head
against proxies, ScopedTypeVariables, AllowAmbiguousTypes, and the
like) so it seems it would make sense to provide it directly
from the library.  However, if there's some reason this function can't
or shouldn't be provided I'd be happy to be enlightened.

Add `censor` function to Capability.Writer

---

ChangeLog.md
capability.cabal
stack-ghc9.yaml
stack-ghc9.yaml.lock

* Bump dependency version numbers
A GHC 9.0 compatible version of generic-lens has been released meanwhile
* Update the tested-with section to include GHC 9.0.1
* Update Changelog
* Bump version number to 0.5.0.0
I've decided on a major version update since the removal of `Capability.Writer.Discouraged` can be viewed as a breaking change.
The package candidate on Hackage can be found here: https://hackage.haskell.org/package/capability-0.5.0.0/candidate

Release 0.5.0.0

---

.github/workflows/ci.yaml
ChangeLog.md
capability.cabal
src/Capability/Error.hs
src/Capability/State/Internal/Strategies.hs
src/Capability/Writer.hs
stack-ghc9.yaml
stack-ghc9.yaml.lock

* Bump the `lens` dependency version bound. (This was raised [on Stackage nightly](https://github.com/commercialhaskell/stackage/issues/6486#issuecomment-1073120594))
* Fix compatibility issues with GHC 9.2.2, see [Ghc 9.2.x migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2#undecidableinstances-no-longer-implies-flexiblecontexts-in-instance-declarations).
* Update `stack` CI pipeline to test on GHC 9.2.2.
* Update changelog
* Bump version number
The package candidate on Hackage can be found here: https://hackage.haskell.org/package/capability-0.5.0.1/candidate

Release 0.5.0.1

---

capability.cabal

As [pointed out by Stackage](https://github.com/commercialhaskell/stackage/issues/6678) the latest lens 5.2 is out of bounds.
I've tested lens 5.2 with GHC 9.4 with `cabal v2-test` and capability's tests pass without any changes beyond the version bound.
I'll create a new Hackage revision on the latest capability release to incorporate this version bump.

Bump version bound on lens

---

capability.cabal

Update the version bounds on the `primitive` dependency to address https://github.com/commercialhaskell/stackage/issues/6887.
Tested with GHC 9.2.5 with
```
$ cabal v2-configure --constraint=primitive==0.8.0.0 --allow-newer=primitive
$ cabal v2-build
$ cabal v2-test
```
The `--allow-newer` flag was needed due to a conflict between `primitive` and the version bounds on `vector-algorithms-0.9.0.1`.
I also used this opportunity to update the `tested-with` field to reflect the GHC versions used on CI.
I'll create a new Hackage revision on the latest capability release to incorporate this version bump.

Bump version bound on primitive

---

capability.cabal

To address https://github.com/commercialhaskell/stackage/issues/7408
Tested with
```
$ cabal v2-configure --constraint=lens==5.3.2
$ cabal v2-build
$ cabal v2-test
```
I'll create a new Hackage revision as well.

Bump version bound for lens
